In [ ]:
import numpy as np
import time

print("NUMPY DATA EXPLORER PROJECT\n")

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(1, 11)
arr3 = np.random.randint(1, 100, size=(3, 3))

print("1D Array:", arr1)
print("Range Array:", arr2)
print("2D Random Array:\n", arr3)

print("\nIndexing & Slicing")
print("First element:", arr1[0])
print("Slice (1 to 3):", arr1[1:4])
print("2D Element [1,2]:", arr3[1, 2])

print("\nMathematical Operations")
print("Addition:", arr1 + 10)
print("Multiplication:", arr1 * 2)
print("Square Root:", np.sqrt(arr1))

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("\nAxis-wise Operations")
print("Row-wise Sum:", np.sum(matrix, axis=1))
print("Column-wise Sum:", np.sum(matrix, axis=0))

print("\nStatistical Operations")
print("Mean:", np.mean(arr2))
print("Median:", np.median(arr2))
print("Max:", np.max(arr2))
print("Min:", np.min(arr2))
print("Standard Deviation:", np.std(arr2))

reshaped = arr2.reshape(2, 5)
print("\nReshaped Array:\n", reshaped)

broadcasted = reshaped + 5
print("Broadcasted Array (+5):\n", broadcasted)

np.save("saved_array.npy", arr3)
loaded_array = np.load("saved_array.npy")

print("\nSaved and Loaded Array:\n", loaded_array)

size = 1000000

python_list = list(range(size))
numpy_array = np.arange(size)

start = time.time()
python_list_result = [x * 2 for x in python_list]
python_time = time.time() - start

start = time.time()
numpy_array_result = numpy_array * 2
numpy_time = time.time() - start

print("\nPerformance Comparison")
print("Python List Time:", python_time)
print("NumPy Array Time:", numpy_time)

print("\nConclusion: NumPy is significantly faster than Python lists.")


NUMPY DATA EXPLORER PROJECT

1D Array: [1 2 3 4 5]
Range Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Random Array:
 [[95 48 15]
 [84 34 50]
 [ 2 86 40]]

Indexing & Slicing
First element: 1
Slice (1 to 3): [2 3 4]
2D Element [1,2]: 50

Mathematical Operations
Addition: [11 12 13 14 15]
Multiplication: [ 2  4  6  8 10]
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]

Axis-wise Operations
Row-wise Sum: [ 6 15]
Column-wise Sum: [5 7 9]

Statistical Operations
Mean: 5.5
Median: 5.5
Max: 10
Min: 1
Standard Deviation: 2.8722813232690143

Reshaped Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Broadcasted Array (+5):
 [[ 6  7  8  9 10]
 [11 12 13 14 15]]

Saved and Loaded Array:
 [[95 48 15]
 [84 34 50]
 [ 2 86 40]]

Performance Comparison
Python List Time: 0.11261653900146484
NumPy Array Time: 0.004365205764770508

Conclusion: NumPy is significantly faster than Python lists.


In [1]:
import pandas as pd

df = pd.read_csv(r'C:\Users\meetr\OneDrive\Documents\data.csv')
print("--- Head (First 5 rows) ---")
print(df.head())

print("\n--- Tail (Last 5 rows) ---")
print(df.tail())

print("\n--- Data Types ---")
print(df.dtypes)

print("\n--- Summary Statistics (Data_value) ---")
print(df['Data_value'].describe())  # Gives count, mean, std, min, 25%, 50%, 75%, max

mean_val = df['Data_value'].mean()
median_val = df['Data_value'].median()
min_val = df['Data_value'].min()
max_val = df['Data_value'].max()
count_val = df['Data_value'].count()

print(f"\nSpecific Stats for 'Data_value':")
print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Min: {min_val}")
print(f"Max: {max_val}")
print(f"Count: {count_val}")


filtered_df = df[df['Series_title_1'] == 'Sales (operating income)']

selected_columns = filtered_df[['Period', 'Data_value', 'Series_title_1', 'STATUS']]

subset_slice = selected_columns.iloc[:50]

print("\n--- Filtered & Sliced Data (First 5 rows) ---")
print(subset_slice.head())

output_filename = 'filtered_sales_data.csv'
subset_slice.to_csv(output_filename, index=False)
print(f"\nProject complete: Filtered results saved to '{output_filename}'")

--- Head (First 5 rows) ---
  Series_reference   Period  Data_value Suppressed STATUS    UNITS  Magnitude  \
0    BDCQ.SF1AA2CA  2016.06    1116.386        NaN      F  Dollars          6   
1    BDCQ.SF1AA2CA  2016.09    1070.874        NaN      F  Dollars          6   
2    BDCQ.SF1AA2CA  2016.12    1054.408        NaN      F  Dollars          6   
3    BDCQ.SF1AA2CA  2017.03    1010.665        NaN      F  Dollars          6   
4    BDCQ.SF1AA2CA  2017.06    1233.700        NaN      F  Dollars          6   

                          Subject  \
0  Business Data Collection - BDC   
1  Business Data Collection - BDC   
2  Business Data Collection - BDC   
3  Business Data Collection - BDC   
4  Business Data Collection - BDC   

                                             Group            Series_title_1  \
0  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
1  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
2  Industry by financi

In [3]:
import pandas as pd


file_path = r'C:\Users\meetr\OneDrive\Documents\data.csv'
df = pd.read_csv(file_path)

print("--- Head (First 5 rows) ---")
print(df.head())

print("\n--- Data Types ---")
print(df.dtypes)

print("\n--- Summary Statistics (Data_value) ---")

print(df['Data_value'].describe())

print(f"Mean: {df['Data_value'].mean()}")
print(f"Median: {df['Data_value'].median()}")

filtered_df = df[df['Series_title_1'] == 'Sales (operating income)']

selected_cols = filtered_df[['Period', 'Data_value', 'Series_title_1', 'STATUS']]

subset_slice = selected_cols.iloc[:50]

print("\n--- Filtered & Sliced Data (First 5 rows) ---")
print(subset_slice.head())

subset_slice.to_csv('filtered_sales_data.csv', index=False)
print("\nProject complete: Filtered results saved to 'filtered_sales_data.csv'")

--- Head (First 5 rows) ---
  Series_reference   Period  Data_value Suppressed STATUS    UNITS  Magnitude  \
0    BDCQ.SF1AA2CA  2016.06    1116.386        NaN      F  Dollars          6   
1    BDCQ.SF1AA2CA  2016.09    1070.874        NaN      F  Dollars          6   
2    BDCQ.SF1AA2CA  2016.12    1054.408        NaN      F  Dollars          6   
3    BDCQ.SF1AA2CA  2017.03    1010.665        NaN      F  Dollars          6   
4    BDCQ.SF1AA2CA  2017.06    1233.700        NaN      F  Dollars          6   

                          Subject  \
0  Business Data Collection - BDC   
1  Business Data Collection - BDC   
2  Business Data Collection - BDC   
3  Business Data Collection - BDC   
4  Business Data Collection - BDC   

                                             Group            Series_title_1  \
0  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
1  Industry by financial variable (NZSIOC Level 2)  Sales (operating income)   
2  Industry by financi